CREATE TABLE APPELER (
    ID_MUNICIPAL BIGINT NOT NULL,
    ID_TECHNICIEN BIGINT NOT NULL, 
    DATE_SERVICE DATE NOT NULL,

    -- Définition de la clé primaire composée
    PRIMARY KEY (ID_MUNICIPAL, ID_TECHNICIEN, DATE_SERVICE),

    -- Définition de la première clé étrangère (vers MUNICIPAL)
    CONSTRAINT FK_APPELER_MUNICIPAL
        FOREIGN KEY (ID_MUNICIPAL)
        REFERENCES MUNICIPAL(ID_MUNICIPAL)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    -- Définition de la deuxième clé étrangère (vers TECHNICIEN)
    CONSTRAINT FK_APPELER_TECHNICIEN
        FOREIGN KEY (ID_TECHNICIEN)
        REFERENCES TECHNICIEN(ID_TECHNICIEN)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);