CREATE TABLE CITOYEN (
    ID_CITOYEN BIGINT NOT NULL AUTO_INCREMENT,
    NOM VARCHAR(100) NOT NULL, 
    PRENOM VARCHAR(100) NOT NULL,
    CIN VARCHAR(20) UNIQUE,
    LIEU_NAISSANCE VARCHAR(100),
    TELEPHONE VARCHAR(20) UNIQUE,
    EMAIL VARCHAR(150) UNIQUE,
    DATE_NAISSANCE DATE,
    -- CORRECTION : Spécifiez BIGINT comme type de donnée pour la clé étrangère
    ID_REGION BIGINT, 

    PRIMARY KEY (ID_CITOYEN),

    CONSTRAINT FK_CITOYEN_REGION
        FOREIGN KEY (ID_REGION)
        REFERENCES REGION(ID_REGION)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);