CREATE TABLE SIGNALEMENT (
    ID_SIGNALEMENT BIGINT NOT NULL AUTO_INCREMENT,
    ID_CITOYEN BIGINT NOT NULL,
    DESCRIPTION TEXT NOT NULL, 
    LOCALISATION VARCHAR(255),
    DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUT VARCHAR(50) NOT NULL DEFAULT 'En attente',
    PREUVE VARCHAR(255),
    COMMENTAIRE TEXT,

    PRIMARY KEY (ID_SIGNALEMENT),

    CONSTRAINT FK_SIGNALEMENT_CITOYEN
        FOREIGN KEY (ID_CITOYEN)
        REFERENCES CITOYEN(ID_CITOYEN)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);